force-app/main/default/objects/Asset/fields/Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Batch_Number__c</fullName>
    <label>Batch Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/On_Order__c.field-meta.xml
<CustomField>
    <fullName>On_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>On Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Orders Recieved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opportunity Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Shortfall__c.field-meta.xml
<CustomField>
    <fullName>Shortfall__c</fullName>
    <formula>( Quantity__c   -  On_Order__c- Stock_On_Hand__c -  Order__c -   Product__r.Total_Quantity__c    ) +Product__r.Rejected_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reorder point</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Stock_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Stock_On_Hand__c</fullName>
    <formula>Product__r.Approved_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stock On Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Under_QA__c.field-meta.xml
<CustomField>
    <fullName>Under_QA__c</fullName>
    <formula>Product__r.Total_Quantity__c -  Product__r.Approved_Quantity__c - Product__r.Rejected_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Under QA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Pending_Quantityy1__c.field-meta.xml
<CustomField>
    <fullName>Pending_Quantityy1__c</fullName>
    <label>Pending Quantity1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>OrderItem.Quantity</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Received_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Received_Quantity__c</fullName>
    <label>Received Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Approved_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Approved_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Approved Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Rejected_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Defective Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/orderdetails.cls
public  class orderdetails {
    @AuraEnabled
    public static List < OrderItem > fetchOrderProduct() {

        return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber,Order.Under_QA__c,Order.Account.Name, Order.Quantity__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status from OrderItem];    
    }
    @AuraEnabled
    public static List<Order> updateOrder(string ordervalue,integer valueRquantity) {
        System.debug('ordervalue :: ' + ordervalue + 'valueee'+ valueRquantity );
        List<Order> ordlistquery = [Select id,Quantity__c,Received_Quantity__c,Order.On_Hand_Recieved__c,Under_QA__c,Pending_Quantityy1__c,Status,Product__c from Order where id=:ordervalue];
        List<Inventory__c> invlist = [SELECT Id,Product__c,On_Order__c,Order__c FROM Inventory__c WHERE Product__c = : ordlistquery[0].Product__c ];
        list<Inventory__c> newinvlist = new list<Inventory__c>();
        system.debug('ordlistquery :: ' + ordlistquery);
        for (Inventory__c inv : invlist) {
            inv.On_Order__c=inv.On_Order__c-valueRquantity;
            inv.Order__c=inv.Order__c+valueRquantity;
            newinvlist.add(inv);
        } 
        update newinvlist; 
        List<Order> updateOrderList = new List<Order>();
        for(Order ord:ordlistquery){
            ord.On_Hand_Recieved__c=ord.On_Hand_Recieved__c+valueRquantity;
            ord.Under_QA__c= ord.Under_QA__c   + valueRquantity;
            ord.Received_Quantity__c = 0;
            ord.Pending_Quantityy1__c = ord.Pending_Quantityy1__c - valueRquantity;
            updateOrderList.add(ord);


        } 
        system.debug('line 20');
        update  updateOrderList;
        system.debug('line 22');  
        return   updateOrderList;  
    }

    /*@AuraEnabled
    public static List<Order> updatePendingQuantity(integer recquantity){
        System.debug('Line 25');
        List<Order> ordrList = [select id,Received_Quantity__c,Pending_Quantityy1__c from Order];
        System.debug('Line 27' + ordrList);
        List<Order> orderPendingList = new List<Order>();
        for(Order ords:ordrList){
            
            System.debug('Line 30'+ords);
            orderPendingList.add(ords);
        }
        System.debug('Line 33'+orderPendingList);

        update orderPendingList;
        return orderPendingList;
    }*/

    @AuraEnabled
    public static void createAsset(String prodId,List<Object> batchNumbers,string orderid) {
        System.debug('Returmnmed cdata'+prodId+''+batchNumbers);
        OrderItem ordObj =[select id,Product2Id,Order.AccountId,Order.Id from OrderItem  where Product2Id=:prodId LIMIT 1];
        List<Asset> assetObjList = new List<asset>();
        integer len = batchNumbers.size();
        for(integer i=0;i<len;i++){
            Asset astObj = new Asset();
            astObj.Product2Id = prodId;
            astObj.Name = 'Asset Delivery'+i;
            astObj.AccountId=ordObj.Order.AccountId;
            astObj.Quantity=1.00;
            astObj.Order_Id__c=Id.valueOf(orderid);
            astObj.Batch_Number__c = (String)batchNumbers[i];
            assetObjList.add(astObj);
        }
        System.debug('list'+assetObjList);
        insert assetObjList;
        System.debug('inserted');
        
    }

    @AuraEnabled
    public static List<string> getproductnamerecords() {
         List<string> productlist=new List<string>();
         List<Product2> returnlist=[Select Id, Name From Product2];
        for (Product2 product : returnlist) {
            productlist.add(product.Name);  
        }
        return productlist;     

    }
    @AuraEnabled
    public static List < OrderItem > retrieveProductRecords(String searchsname) {
        

        return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber,Order.Under_QA__c, Order.Quantity__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status from OrderItem where Product2.Name LIKE:searchsname];    
    }

    @AuraEnabled
    public static List < Inventory__c > retrieveProductNameRecords(String searchsproductname) {
        

        return [ select id, Warehouse__r.Name, Product__r.name, Quantity__c, Stock_On_Hand__c, On_Order__c, Product__r.Rejected_Quantity__c, Order__c, Under_QA__c, Shortfall__c from Inventory__c where Product__r.name LIKE:searchsproductname];
    }
    
    // @AuraEnabled(cacheable=true)
    // public static List<string> getStatusRecords() {
    //      List<string> orderlist=new List<string>();
    //      List<Order> returnlist=[Select Id, Status From Order];
    //     for (Order odrs : returnlist) {
    //         orderlist.add(odrs.status);     
    //     }
    //     return orderlist;     

    // }
    @AuraEnabled   
    public static List < OrderItem > statusRecords(String searchstatus, String searchsname) {
        if(searchstatus=='All'){
            return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber,Order.Under_QA__c, Order.Quantity__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status from OrderItem where Product2.Name LIKE:searchsname];        }
            



            else if (searchstatus=='All' && searchsname=='All') {

        return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber, Order.Quantity__c,Order.Under_QA__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status from OrderItem];
    }else if(searchsname=='All'){
        return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber,Order.Under_QA__c, Order.Quantity__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status from OrderItem where Order.Status LIKE:searchstatus ];    

    }else {
        return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber,Order.Under_QA__c, Order.Quantity__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status from OrderItem where Order.Status LIKE:searchstatus AND Product2.Name LIKE:searchsname];    

    }
        
            

    }

    // @AuraEnabled   
    // public static List < Inventory__c > productRecords(String searchstatus) {
    //     if(searchstatus=='All'){
    //         return [ select id, Warehouse__r.Name, Product__r.name, Quantity__c, Stock_On_Hand__c, On_Order__c, Product__r.Rejected_Quantity__c, Order__c, Under_QA__c, Shortfall__c from Inventory__c where Product__r.name LIKE:searchstatus];      
    //     }   
    // }

    @AuraEnabled   
        public static List<OrderItem> getOrderId(String searchKey) {
            String key = '%' + searchKey + '%';
            return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber,Order.Under_QA__c, Order.Quantity__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status,Order.Approved_Quantity__c,Order.On_Hand_Recieved__c,Order.Reject_Quantity__c from OrderItem where Order.OrderNumber LIKE :key];
        }


        @AuraEnabled    
        public static List < OrderItem > statusRecordsWithoutProduct(String searchstatus) {
            //if(searchstatus=='All'){
               // return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber, Order.Quantity__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status from OrderItem where Product2.Name LIKE:searchsname];        }
               // else{
                if(searchstatus=='All'){
                    return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber,Order.Under_QA__c, Order.Quantity__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status from OrderItem];    


                }else{
                    return[Select id,Product2.Name,Product2Id,OrderId, Order.OrderNumber,Order.Under_QA__c, Order.Quantity__c,Order.Received_Quantity__c,Order.Pending_Quantityy1__c, Order.Status from OrderItem where Order.Status LIKE:searchstatus];    

                }
    
    
    
               // }
    
        }
    
        @AuraEnabled
    public static List < OrderItem > QAManagerOrderProduct() {

        return[SELECT Order.OrderNumber, Product2.Name,Order.Pending_Quantityy1__c,Order.Id,Order.Under_QA__c, Product2.Approved_Quantity__c, Product2.Rejected_Quantity__c from OrderItem WHERE Product2.Name='Calculator' ];    
    }

    @AuraEnabled   
        public static integer getAssetRecords(String assetRecs) {
        integer AssetListSize=0;
        list<Asset> assetlist=[SELECT Id,Order_Id__c from Asset Where Order_Id__c =: assetRecs];
        AssetListSize=assetlist.size();
        return AssetListSize;

        }

}