force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/On_Order__c.field-meta.xml
<CustomField>
    <fullName>On_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>On Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Orders Recieved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opportunity Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Shortfall__c.field-meta.xml
<CustomField>
    <fullName>Shortfall__c</fullName>
    <formula>( Quantity__c   -  On_Order__c- Stock_On_Hand__c -  Order__c -   Product__r.Total_Quantity__c    ) +Product__r.Rejected_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reorder point</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Stock_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Stock_On_Hand__c</fullName>
    <formula>Product__r.Approved_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stock On Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Under_QA__c.field-meta.xml
<CustomField>
    <fullName>Under_QA__c</fullName>
    <formula>Product__r.Total_Quantity__c -  Product__r.Approved_Quantity__c - Product__r.Rejected_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Under QA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Rejected_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Defective Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExampleController.cls
public  class ExampleController {
    @AuraEnabled
    public static List < Inventory__c > fetchInventory() {

            return [ select id, Warehouse__r.Name, Product__r.name, Quantity__c, Stock_On_Hand__c, On_Order__c, Product__r.Rejected_Quantity__c, Order__c, Under_QA__c, Shortfall__c from Inventory__c];
       
    }

    @AuraEnabled(cacheable=true)
    public static List < Opportunity > fetchOpportunity() {
        return [select name, (select Product2Id from Opportunitylineitems) from opportunity];   
    }

    // @AuraEnabled(cacheable=true)
    // public static List<string> getwarehousenamerecords() {
    //      List<string> warehouselist=new List<string>();
    //      List<Inventory__c> returnlist=[Select Id, Warehouse__r.Name From Inventory__c];
    //     for (Inventory__c invn : returnlist) {
    //         warehouselist.add(invn.Warehouse__r.Name);  
    //     }
    //     return warehouselist;     

    // }

    @AuraEnabled(cacheable=true)
    public static List<string> getwarehousenamerecords() {
         List<string> warehouselist=new List<string>();
         List<Schema.Location> returnlist=[Select Id,Name From Location];
        for (Schema.Location loc : returnlist) {
            warehouselist.add(loc.Name);  
        }
        return warehouselist;     

    }

    @AuraEnabled(cacheable=true)
    public static List < Inventory__c > retrieveWarehouseRecords(String searchsname) {
        
        return [ select id, Warehouse__r.Name, Product__r.name, Quantity__c, Stock_On_Hand__c, On_Order__c, Product__r.Rejected_Quantity__c, Order__c, Under_QA__c, Shortfall__c from Inventory__c where Warehouse__r.Name LIKE:searchsname];
    }
}